[package]
name = "crossword-collab-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
futures = "0.3.31"
tokio-stream = "0.1.16"
sqlx = { version = "0.8", features = [ "runtime-tokio", "postgres"] }